services:
  web:
    image: ghcr.io/solver57/solver57:main
    env_file: .env
    build: .
    restart: always
    ports:
      - '8000:8000'
  db:
    image: postgres:latest
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    user: postgres
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: