services:
  web:
    image: ghcr.io/solver57/solver57:main
    env_file: .env
    build: .
    restart: always
    ports:
      - '8000:8000'
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:latest
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    user: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
      start_interval: 1s

volumes:
  postgres_data: